### PR TITLE
Enable Travis and Appveyor, fix errors detected on Linux

### LINKED ISSUE #1: Build system level up
- [x] remove dust from the project build system
- [x] add CMake files
- [x] enable Appveyor
- [x] enable Travis

### PR DESCRIPTION
**Pull request by ForNeVeR**
- add support for Travis (Linux) and Appveyor (Windows)
- enable platform detection according to known data from [Pre-defined Compiler Macros](https://sourceforge.net/p/predef/wiki/OperatingSystems/) wiki
- officially enabled C++14 (because we rely on `std::to_string` etc.)
- remove usage of outdated and unsupported constructs (`ltoa`, some not-so-valid casts and coding styles only allowed by Visual Studio)
- close #1

### CODE REVIEW

File: source/classes/ic_file.h [hunk 1]
```diff
@@ -130,12 +130,12 @@ void ic_file::close()
 /**
  * Reads bytes from file into ic_string and returns it.
  * @param size Number of bytes to read from file.
- * @return Flag indicating success of the operation.
+ * @return Data loaded from file or nullptr.
  */
 ic_string *ic_file::read(long size)
 {
   // is file open and readable?
-  if(!(mMode && IO_READ)) return false;
```
Comment (impworks) [inline source/classes/ic_file.h:138]: Woah, can't believe the compiler didn't alert about this one.

Comment (ForNeVeR) [reply source/classes/ic_file.h:138]: That surprised me, too.

**Review by impworks — APPROVED** [review]

**Comment by ForNeVeR** [comment]
Thanks for the review!
